### ISSUE TITLE
images size 4 is not usable size

### ISSUE THREAD

**Issue by optikalefx** [500px/api-documentation#129]
I have an Image that is 527x1170. It's long.  The max size returned by size 4 in the API is 406x900.  That 900 tells me that size 4 doesn't give a height greater than 900?

**Comment by cdmicacc** [comment]
Size 4 is defined as 900 pixels on the longest edge.  Because your photo is taller than it is wide, this results in a photo that is 900 pixels high.  If your photo had been 1170x527 you'd have gotten an image that is 900x406 instead.  See the [documentation on image sizes](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes).

**Comment by optikalefx** [comment]
Thanks, is 2048 going to be deprecated?  The current docs state "image_size — The photo size to be returned. It has to be an integer: 1 to 4. Also an array is accepted:"

2048 gives me what I'm looking for which is great, but apigee and the docs don't show that was possible.

**Comment by cdmicacc** [comment]
No, it won't be -- those docs you're referencing are out of date.  I'll update them now.  Thanks for letting us know!.
