### ISSUE TITLE
`GET photos` parameter documentation unclear for `only` and `exclude`

### ISSUE THREAD

**Issue by machx0r** [500px/api-documentation#144]
The documentation for the `only` and `exclude` parameters of the `GET photos` call are not clear. It states:

*String name of the category to return photos from. Note: Case sensitive, separate multiple values with a comma.*

But this is not 100% accurate. From my experimentation it seems the following are true:

1. Category cannot contain a space (ie: "Fine Art" becomes "FineArt").
2. Case sensitivity only matters for multi-word categories. Ex: "nude", "NUDE", and "NuDe" all filter correctly but only "FineArt" works.
3. There is no way to filter on "Black and White" or "City and Architecture". I've tried many combinations and none work (ie: "BlackandWhite", "BlackAndWhite", "Black_and_White", "Black&White", "Black+White", etc.)

Through trial and error I've been able to work around issues 1 and 2 but cannot figure out issue 3 so any help there is much appreciated.

Ultimately it could clear up a lot if these fields accepted the category ID rather than string name.

**Comment by Melraidin** [comment]
The ```only``` and ```exclude``` parameters must be URL encoded. Replace spaces with +, e.g.:
```/v1/photos?feature=popular&only=Black+and+White```

Agreed that this isn't strictly case-sensitive. For historical reasons there's some cleanup performed on the category names provided but this additional processing should be removed in the future and so hasn't been documented in the API.

Accepting category IDs instead of category names would be preferable and may be able to be fit into a future iteration.

Thanks for your feedback!

**Comment by machx0r** [comment]
@Melraidin, thanks for the clarification. After reviewing my code I see that my problem was that I was double URL encoding the category filter values so the spaces became %2520 instead of the correct %20. The fact that all two word categories worked without any spaces threw me off track :) Thanks again!
