### ISSUE TITLE
Request for guidance

### ISSUE THREAD

**Issue by cpare** [500px/api-documentation#220]
Hello - I am trying to fetch a randomized background image to use as a background on an intranet site, looking for some guidance on how to best do this search:

- Should we roll the dice and accept whatever the community has selected to keep things fresh?
- If we do opt for community popular images, how do we make sure they are always Landscape and SWF?
- If we just wanted to select form the list we "liked" under our account, how would that look?
- Is their any other guidance we should be aware of to prevent licensing/usage issues, even on an internal site?

Sample URL I have been working with, though the NSFW part doesn't seem to be respected.
`https://api.500px.com/v1/photos?feature=user_favorites&user_id=<<UserID>>&password=<<password>>&sort=rating&image_size=2048&include_store=store_download&include_states=voted&consumer_key=<<ConsumerKey>>&term=%7Bnsfw%3A1%7D`

**Comment by mck182** [comment]
Hey there,

I'll respond to your points one by one:

> *Should we roll the dice and accept whatever the community has selected to keep things fresh?

You certainly can, you can also limit your selection
only to a particular category, say Landscapes or
Urban exploration.

> * If we do opt for community popular images, how do we make sure they are always Landscape and SWF?

The only way to make sure they are all landscape
is to check them yourself, each JSON photo object
will have the photo dimensions, so before actually
fetching the photo, you should be able to check it.

As for SFW, we try our best to ensure all NSFW are
properly marked, but unfortunately we cannot
guarantee that this will always be the case.

> * If we just wanted to select form the list we "liked" under our account, how would that look?

Your best bet would be to add them to a gallery and
then fetch the gallery. For more details please read
through the Gallery endpoints, particularly this one:
https://github.com/500px/api-documentation/blob/master/endpoints/galleries/GET_galleries_id_items.md


> * Is their any other guidance we should be aware of to prevent licensing/usage issues, even on an internal site?

You can use the photos returned by the API as long
as your usage complies with the API terms of use:
https://github.com/500px/api-documentation/blob/master/basics/terms_of_use.md

Also note that because you'll need a consumer key
to fetch the photos and that will be linked to your
500px profile, you should also make sure you don't
violate the 500px terms of service, those you can
read here: 
https://about.500px.com/terms/

Hope that helps! Feel free to ask other questions.

Best wishes,
Martin from 500px
