### ISSUE TITLE
feature=user not working for mail address

### ISSUE THREAD

**Issue by mvysny** [500px/api-documentation#230]
Good day, when polling the following URL:

https://api.500px.com/v1/photos?feature=user&username=foo%40bar.baz&page=1&rpp=100&image_size=2048

the response is
```
{"error":"You have not provided a valid username or user ID.","status":400}
```

Maybe the username (which is an email address in this case, it is valid but I have replaced it with a dummy one here) contains an escaped character?
Thanks!

**Comment by mvysny** [comment]
Basically what I'm trying to do is to show all images for logged-in user. Maybe there is another way?

**Comment by mck182** [comment]
Hey Martin,

each user has an actual username, which is not necessarily
an email. Are you using the user's email or the actual username?
Can you provide an actual username (that's not the user's email)
so that we can verify? Alternatively, you can also use the user's
id. Both the `id` and `username` can be obtained from
`GET /users`.

Hope that helps!

Martin, 500px
(zdravím na Slovensko!)

**Comment by mvysny** [comment]
Hey Martin, thanks for the reply. It is indeed as you described: accidentally I was passing a mail address I use for login, instead of the actual 500px username. Using the "username" JSON field from `/users` helped - thanks!
Since it was my fault, I propose to close this as WON'T FIX.
(zdravim do Kanady? :-)

**Comment by mck182** [comment]
Glad I could help! :)

Martin, 500px
(jop, Toronto :)
