### ISSUE TITLE
Geo location query returns photos with coordinates of (0, 0)

### ISSUE THREAD

**Issue by jameslin123** [500px/api-documentation#245]
A search of the following form would return photos of latitude and longitude of zero. 

https://api.500px.com/v1/photos/search?geo=10,10,50000km 

(0, 0) is on the ocean, south west to the African continent, and it's extremely unlikely that such photos are relevant to that precise location, according to their content.

If you do a search with a search radius covering (0, 0), chances are that some or even most of the results will fall into that (0,0) location, which renders the query ineffective.

Is this a known issue, or am I doing it wrong? Can we filter out photos with latitude and longitude of exact zeros?

**Comment by mck182** [comment]
Hi there,

your search query as you posted it will of course include
the geo coords `(0, 0)` as it is covered by the radius in
your query.

That said, radius of `50000km` doesn't really make that
much sense as it includes the entire planet.

Finally, the search endpoint with geo parameter is meant
more for a local search, ie. down to a city or region level,
not really for global scale like that (say more than 500km).

With that in mind we don't see a need to provide a way
to filter out photos with coords `(0, 0)` as ideally your
local region radius would never include them (because
it's in the middle of ocean-nowhere).

Hope that helps!

Cheers,
Martin, 500px

**Comment by jameslin123** [comment]
Hey Martin,

Thank you for the explanation! 
If the geo search is designed for local search only, then I agree it isn't a high priority to fix the (0, 0) issue. 

Yeah 50000km is not a real use case, just a quick way to ensure the (0, 0) point lies inside the search radius :)
